source("./scripts/cargadelibrerias.R")
rm(list=ls())
source("./scripts/cargaypreprocesado.R")
rm(list=ls())
source("./scripts/estadisticos.R")
rm(list=ls())
source("./scripts/graficos.R")
rm(list=ls())
source("./scripts/modelado.R")
rm(list=ls())

source("./scripts/cargaypreprocesado_api.R")
r <- plumb("./scripts/api.R")
r$run(port=8000)